version: "3"

services:
  mtproxy:
    build: .
    container_name: mtproxy
    restart: always
    ports:
      - 44334:9000
    volumes:
      - ./config:/data
    environment:
      - SECRET_COUNT=1
